name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    
jobs:

  code-analysis-and-testing:
    name: Code analysis and testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1.4.0
      with:
        channel: 'stable'

    - name: Get pub dependencies
      run: flutter pub get

    - name: Flutter analyze
      run: flutter analyze

    - name: Flutter test
      run: flutter test
 
    - name: Prepare Secret Files
      run: |
        echo "${{ secrets.KEYSTORE }}" > key.jks.asc
        gpg -d --passphrase "${{ secret.KEYSTORE_PASSPHRASE }}" --batch key.jks.asc > app/key.jks
        # echo "${{ secret.KEYSTORE_PROPERTIES }}" > key.properties.asc
        # gpg -d --passphrase "${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}" --batch keystore.properties.asc > keystore.properties   
        # echo "${{ secrets.AGCONNECT_SERVICES }}" > agconnect-services.json.asc    
        # gpg -d --passphrase "${{ secrets.AGCONNECT_SERVICES_PASSPHRASE }}" --batch agconnect-services.json.asc > app/agconnect-services.json
