name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [ master, main ]
  # pull_request:
    # branches: [ master, main ]
    # This ignores PR from any branches to master branch.
    # branches-ignore:
    #   - 'master'
      
    
jobs:

  code-analysis-and-testing:
    name: Code analysis and testing
    runs-on: ubuntu-latest

    # env:
    #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    # timeout-minutes: 30
    steps:
    # - uses: act10ns/slack@v1      
    #   with:
    #     status: starting
    #     # channel: '#workflows'
    #   if: always()


    # - name: Slack Notify Build

    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      with:
        channel_id: C0278LELCMV
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      uses: voxmedia/github-action-slack-notify-build@v1
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      with:
        channel_id: C0278LELCMV
        status: STARTED
        color: danger
      


    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: slack - GitHub Actions Slack integration
    #   uses: act10ns/slack@v1.2.2
    #   with:
    #       status: starting
    #   if: always()
      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Variables
      id: vars
      run: echo "::set-output name=SHORT_COMMIT_ID::$(git rev-parse --short HEAD)"
      
    


    # - name: Slack Notify Build
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
    #   uses: abinoda/slack-action@master
    #   with:
    #     args: '{\"channel\":\"C0278LELCMV\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'


    - name: Set up Flutter
      uses: subosito/flutter-action@v1.4.0
      with:
        channel: 'stable'

    - name: Flutter clean
      run: flutter clean

    - name: Get pub dependencies
      run: flutter pub get

    # - name: Flutter analyze
    #   run: flutter analyze

    # - name: Flutter test
    #   run: flutter test
 
    - name: Prepare Secret Files
      run: |
        echo "${{ secrets.KEYSTORE }}" > upload-keystore.jks.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch upload-keystore.jks.asc > upload-keystore.jks

        echo "${{ secrets.KEYSTORE_PROPERTIES }}" > key.properties.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}" --batch key.properties.asc > key.properties   
        
        # echo "${{ secrets.AGCONNECT_SERVICES }}" > agconnect-services.json.asc    
        # gpg -d --passphrase "${{ secrets.AGCONNECT_SERVICES_PASSPHRASE }}" --batch agconnect-services.json.asc > app/agconnect-services.json    
    
    - name: Build APK
      run: flutter build appbundle
    
    - name: Upload APK artifact 
      uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.FS_ANDROID_SERVICE_ACCOUNT_JSON }}
        packageName: com.inapp_purchase_test
        releaseFile: build/app/outputs/bundle/release/app-release.aab
        releaseFiles: build/app/outputs/bundle/release/*.aab
        track: alpha
        inAppUpdatePriority: 2
        userFraction: 0.33
        # whatsNewDirectory: distribution/whatsnew
        # mappingFile: app/build/outputs/mapping/release/mapping.txt

    # - uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     steps: ${{ toJson(steps) }}
    #   if: always()